# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :bump_xcode_version do |options|
    increment_version_number_in_xcodeproj(version_number: options[:version_number])
    increment_build_number_in_xcodeproj(build_number: "1")
  end

  lane :bump_podspec_version do |options|
    version_bump_podspec(version_number: options[:version_number])
  end
end
