name: Deploy

on: 
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: 'Enter version:'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Pods and Gems
      run: |
        bundle install
        bundle exec pod install
    - name: Create XCFramework
      run: |
        bundle exec fastlane bump_xcode_version version_number:${{ github.event.inputs.version }}
        ./Scripts/build.sh
    - name: Run Workflow
      uses: timheuer/base64-to-file@v1
      with:
        fileName: 'service-account.json'
        encodedString: ${{ secrets.FIREBASE }}
    - name: Install python
      uses: actions/setup-python@v3.1.2
    - name: Install python dependancies
      run: pip install firebase_admin
    - name: Run upload script
      id: upload
      run: |
        url=$(python ./Scripts/upload.py ${{ github.event.inputs.version }})
        echo "::set-output name=url::$url"
    - name: Prepare for release
      run: |
        cp Scripts/Template.podspec PMComplitedUserPrinter.podspec
        sed -i '' 's,REMOTE_XCFRAMEWORK_URL,${{ steps.upload.outputs.url }},g' PMComplitedUserPrinter.podspec
        bundle exec fastlane bump_podspec_version version_number:${{ github.event.inputs.version }}
    - name: Release
      run: COCOAPODS_TRUNK_TOKEN=${{ secrets.COCOAPODS_TRUNK_TOKEN }} bundle exec pod trunk push
    
