name: Deploy

on: [workflow_dispatch]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Pods and Gems
      run: |
        bundle install
        bundle exec pod install
    - name: Create XCFramework
      run: |
        ./Scripts/build.sh
