name: Deploy

on: 
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: 'Enter version:'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Pods and Gems
      run: |
        bundle install
        bundle exec pod install
    - name: Create XCFramework
      run: |
        bundle exec fastlane bump_xcode_version version_number:${{ github.event.inputs.version }}
        ./Scripts/build.sh
